version: 1.0.{build}
image: Visual Studio 2017
configuration: Release
platform: Any CPU
install:
- cmd: choco install gitversion.portable -pre -y
before_build:
- ps: >-
    .\init.ps1

    msbuild /t:restore

    gitversion /l console /output buildserver
build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
before_package:
- ps: msbuild /t:pack
test:
  categories:
    except:
    - localOnly
    - Benchmark
artifacts:
- path: '*.nupkg'
  name: NuGet
deploy:
- provider: NuGet
  server: https://www.myget.org/F/qwiq/api/v2/package
  api_key:
    secure: 8wGYx8W+ojYQJsAJpRLez+KwwFa+OW7cvsn5RoR08WQpi5klhTq/9b/9YaEu/5Bx
  symbol_server: https://www.myget.org/F/qwiq/symbols/api/v2/package
notifications:
- provider: GitHubPullRequest
  on_build_success: true
  on_build_failure: true
  on_build_status_changed: true